//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LogicApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        public static string GroupSelection {
            get {
                return ResourceManager.GetString("GroupSelection", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        public static string Progression {
            get {
                return ResourceManager.GetString("Progression", resourceCulture);
            }
        }
        
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        public static string ResumeQuestion {
            get {
                return ResourceManager.GetString("ResumeQuestion", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string DescriptionGroup1 {
            get {
                return ResourceManager.GetString("DescriptionGroup1", resourceCulture);
            }
        }
        
        public static string DescriptionGroup2 {
            get {
                return ResourceManager.GetString("DescriptionGroup2", resourceCulture);
            }
        }
        
        public static string DescriptionGroup3 {
            get {
                return ResourceManager.GetString("DescriptionGroup3", resourceCulture);
            }
        }
        
        public static string DescriptionGroup4 {
            get {
                return ResourceManager.GetString("DescriptionGroup4", resourceCulture);
            }
        }
        
        public static string DescriptionGroup5 {
            get {
                return ResourceManager.GetString("DescriptionGroup5", resourceCulture);
            }
        }
        
        public static string GroupeDescription {
            get {
                return ResourceManager.GetString("GroupeDescription", resourceCulture);
            }
        }
        
        public static string NeverShowAgain {
            get {
                return ResourceManager.GetString("NeverShowAgain", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string NothingResume {
            get {
                return ResourceManager.GetString("NothingResume", resourceCulture);
            }
        }
        
        public static string NothingResumeText {
            get {
                return ResourceManager.GetString("NothingResumeText", resourceCulture);
            }
        }
        
        public static string sgAnimals {
            get {
                return ResourceManager.GetString("sgAnimals", resourceCulture);
            }
        }
        
        public static string sgApparel {
            get {
                return ResourceManager.GetString("sgApparel", resourceCulture);
            }
        }
        
        public static string sgBehaviour {
            get {
                return ResourceManager.GetString("sgBehaviour", resourceCulture);
            }
        }
        
        public static string sgEconomics {
            get {
                return ResourceManager.GetString("sgEconomics", resourceCulture);
            }
        }
        
        public static string sgBody {
            get {
                return ResourceManager.GetString("sgBody", resourceCulture);
            }
        }
        
        public static string sgBuilding {
            get {
                return ResourceManager.GetString("sgBuilding", resourceCulture);
            }
        }
        
        public static string sgClothes {
            get {
                return ResourceManager.GetString("sgClothes", resourceCulture);
            }
        }
        
        public static string sgEducation {
            get {
                return ResourceManager.GetString("sgEducation", resourceCulture);
            }
        }
        
        public static string sgEmotion {
            get {
                return ResourceManager.GetString("sgEmotion", resourceCulture);
            }
        }
        
        public static string sgFood {
            get {
                return ResourceManager.GetString("sgFood", resourceCulture);
            }
        }
        
        public static string sgJob {
            get {
                return ResourceManager.GetString("sgJob", resourceCulture);
            }
        }
        
        public static string sgLeisure {
            get {
                return ResourceManager.GetString("sgLeisure", resourceCulture);
            }
        }
        
        public static string sgNature {
            get {
                return ResourceManager.GetString("sgNature", resourceCulture);
            }
        }
        
        public static string sgOther {
            get {
                return ResourceManager.GetString("sgOther", resourceCulture);
            }
        }
        
        public static string sgPeople {
            get {
                return ResourceManager.GetString("sgPeople", resourceCulture);
            }
        }
        
        public static string sgReligion {
            get {
                return ResourceManager.GetString("sgReligion", resourceCulture);
            }
        }
        
        public static string sgTechnology {
            get {
                return ResourceManager.GetString("sgTechnology", resourceCulture);
            }
        }
        
        public static string sgTransport {
            get {
                return ResourceManager.GetString("sgTransport", resourceCulture);
            }
        }
        
        public static string sgEnvironment {
            get {
                return ResourceManager.GetString("sgEnvironment", resourceCulture);
            }
        }
        
        public static string sgMachinery {
            get {
                return ResourceManager.GetString("sgMachinery", resourceCulture);
            }
        }
        
        public static string sgMedicine {
            get {
                return ResourceManager.GetString("sgMedicine", resourceCulture);
            }
        }
        
        public static string sgMilitary {
            get {
                return ResourceManager.GetString("sgMilitary", resourceCulture);
            }
        }
        
        public static string sgMusic {
            get {
                return ResourceManager.GetString("sgMusic", resourceCulture);
            }
        }
        
        public static string sgNationality {
            get {
                return ResourceManager.GetString("sgNationality", resourceCulture);
            }
        }
        
        public static string sgPolitics {
            get {
                return ResourceManager.GetString("sgPolitics", resourceCulture);
            }
        }
        
        public static string sgProfessions {
            get {
                return ResourceManager.GetString("sgProfessions", resourceCulture);
            }
        }
        
        public static string sgScience {
            get {
                return ResourceManager.GetString("sgScience", resourceCulture);
            }
        }
        
        public static string sgSociety {
            get {
                return ResourceManager.GetString("sgSociety", resourceCulture);
            }
        }
        
        public static string sgSport {
            get {
                return ResourceManager.GetString("sgSport", resourceCulture);
            }
        }
        
        public static string sgTransportation {
            get {
                return ResourceManager.GetString("sgTransportation", resourceCulture);
            }
        }
        
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        public static string GoalsDescription1 {
            get {
                return ResourceManager.GetString("GoalsDescription1", resourceCulture);
            }
        }
        
        public static string GoalsDescription2 {
            get {
                return ResourceManager.GetString("GoalsDescription2", resourceCulture);
            }
        }
        
        public static string GoalsDescription3 {
            get {
                return ResourceManager.GetString("GoalsDescription3", resourceCulture);
            }
        }
        
        public static string MainDescription {
            get {
                return ResourceManager.GetString("MainDescription", resourceCulture);
            }
        }
        
        public static string MainDescription1 {
            get {
                return ResourceManager.GetString("MainDescription1", resourceCulture);
            }
        }
        
        public static string MainDescription2 {
            get {
                return ResourceManager.GetString("MainDescription2", resourceCulture);
            }
        }
        
        public static string MainDescription3 {
            get {
                return ResourceManager.GetString("MainDescription3", resourceCulture);
            }
        }
        
        public static string sgGroup4 {
            get {
                return ResourceManager.GetString("sgGroup4", resourceCulture);
            }
        }
        
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        public static string sgGroup3 {
            get {
                return ResourceManager.GetString("sgGroup3", resourceCulture);
            }
        }
        
        public static string sgGroup5 {
            get {
                return ResourceManager.GetString("sgGroup5", resourceCulture);
            }
        }
        
        public static string sgSubgroup1 {
            get {
                return ResourceManager.GetString("sgSubgroup1", resourceCulture);
            }
        }
        
        public static string sgSubgroup2 {
            get {
                return ResourceManager.GetString("sgSubgroup2", resourceCulture);
            }
        }
        
        public static string sgSubgroup3 {
            get {
                return ResourceManager.GetString("sgSubgroup3", resourceCulture);
            }
        }
        
        public static string sgSubgroup4 {
            get {
                return ResourceManager.GetString("sgSubgroup4", resourceCulture);
            }
        }
        
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        public static string Time_spent {
            get {
                return ResourceManager.GetString("Time_spent", resourceCulture);
            }
        }
        
        public static string sgApparelFood {
            get {
                return ResourceManager.GetString("sgApparelFood", resourceCulture);
            }
        }
        
        public static string sgBuildingsMilitary {
            get {
                return ResourceManager.GetString("sgBuildingsMilitary", resourceCulture);
            }
        }
        
        public static string sgArt {
            get {
                return ResourceManager.GetString("sgArt", resourceCulture);
            }
        }
        
        public static string sgReligionNationalities {
            get {
                return ResourceManager.GetString("sgReligionNationalities", resourceCulture);
            }
        }
        
        public static string word {
            get {
                return ResourceManager.GetString("word", resourceCulture);
            }
        }
        
        public static string sg2_1 {
            get {
                return ResourceManager.GetString("sg2_1", resourceCulture);
            }
        }
        
        public static string sg2_10 {
            get {
                return ResourceManager.GetString("sg2_10", resourceCulture);
            }
        }
        
        public static string sg2_11 {
            get {
                return ResourceManager.GetString("sg2_11", resourceCulture);
            }
        }
        
        public static string sg2_3 {
            get {
                return ResourceManager.GetString("sg2_3", resourceCulture);
            }
        }
        
        public static string sg2_4 {
            get {
                return ResourceManager.GetString("sg2_4", resourceCulture);
            }
        }
        
        public static string sg2_5 {
            get {
                return ResourceManager.GetString("sg2_5", resourceCulture);
            }
        }
        
        public static string sg2_6 {
            get {
                return ResourceManager.GetString("sg2_6", resourceCulture);
            }
        }
        
        public static string sg2_7 {
            get {
                return ResourceManager.GetString("sg2_7", resourceCulture);
            }
        }
        
        public static string sg2_8 {
            get {
                return ResourceManager.GetString("sg2_8", resourceCulture);
            }
        }
        
        public static string sg2_9 {
            get {
                return ResourceManager.GetString("sg2_9", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string Words_K {
            get {
                return ResourceManager.GetString("Words_K", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup1 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup1", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup2 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup2", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup3 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup3", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup4 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup4", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup5 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup5", resourceCulture);
            }
        }
        
        public static string sg2_12 {
            get {
                return ResourceManager.GetString("sg2_12", resourceCulture);
            }
        }
        
        public static string sg3_01 {
            get {
                return ResourceManager.GetString("sg3_01", resourceCulture);
            }
        }
        
        public static string sg3_03 {
            get {
                return ResourceManager.GetString("sg3_03", resourceCulture);
            }
        }
        
        public static string sg3_05 {
            get {
                return ResourceManager.GetString("sg3_05", resourceCulture);
            }
        }
        
        public static string sg3_06 {
            get {
                return ResourceManager.GetString("sg3_06", resourceCulture);
            }
        }
        
        public static string sg3_08 {
            get {
                return ResourceManager.GetString("sg3_08", resourceCulture);
            }
        }
        
        public static string sg3_09 {
            get {
                return ResourceManager.GetString("sg3_09", resourceCulture);
            }
        }
        
        public static string sg3_10 {
            get {
                return ResourceManager.GetString("sg3_10", resourceCulture);
            }
        }
        
        public static string sg3_11 {
            get {
                return ResourceManager.GetString("sg3_11", resourceCulture);
            }
        }
        
        public static string sg3_13 {
            get {
                return ResourceManager.GetString("sg3_13", resourceCulture);
            }
        }
        
        public static string sg3_14 {
            get {
                return ResourceManager.GetString("sg3_14", resourceCulture);
            }
        }
        
        public static string sg3_comp {
            get {
                return ResourceManager.GetString("sg3_comp", resourceCulture);
            }
        }
        
        public static string sgCharacteristics {
            get {
                return ResourceManager.GetString("sgCharacteristics", resourceCulture);
            }
        }
        
        public static string sgIT {
            get {
                return ResourceManager.GetString("sgIT", resourceCulture);
            }
        }
        
        public static string sgLegal {
            get {
                return ResourceManager.GetString("sgLegal", resourceCulture);
            }
        }
        
        public static string sg2_81 {
            get {
                return ResourceManager.GetString("sg2_81", resourceCulture);
            }
        }
        
        public static string sg3_02 {
            get {
                return ResourceManager.GetString("sg3_02", resourceCulture);
            }
        }
        
        public static string sg3_04 {
            get {
                return ResourceManager.GetString("sg3_04", resourceCulture);
            }
        }
        
        public static string sg3_07 {
            get {
                return ResourceManager.GetString("sg3_07", resourceCulture);
            }
        }
        
        public static string sg4_01 {
            get {
                return ResourceManager.GetString("sg4_01", resourceCulture);
            }
        }
        
        public static string sg4_02 {
            get {
                return ResourceManager.GetString("sg4_02", resourceCulture);
            }
        }
        
        public static string sg4_03 {
            get {
                return ResourceManager.GetString("sg4_03", resourceCulture);
            }
        }
        
        public static string sg4_04 {
            get {
                return ResourceManager.GetString("sg4_04", resourceCulture);
            }
        }
        
        public static string sg4_05 {
            get {
                return ResourceManager.GetString("sg4_05", resourceCulture);
            }
        }
        
        public static string sg4_06 {
            get {
                return ResourceManager.GetString("sg4_06", resourceCulture);
            }
        }
        
        public static string sg4_07 {
            get {
                return ResourceManager.GetString("sg4_07", resourceCulture);
            }
        }
        
        public static string sg4_08 {
            get {
                return ResourceManager.GetString("sg4_08", resourceCulture);
            }
        }
        
        public static string sg4_09 {
            get {
                return ResourceManager.GetString("sg4_09", resourceCulture);
            }
        }
        
        public static string sg4_10 {
            get {
                return ResourceManager.GetString("sg4_10", resourceCulture);
            }
        }
        
        public static string sg4_11 {
            get {
                return ResourceManager.GetString("sg4_11", resourceCulture);
            }
        }
        
        public static string sg5_01 {
            get {
                return ResourceManager.GetString("sg5_01", resourceCulture);
            }
        }
        
        public static string sg5_02 {
            get {
                return ResourceManager.GetString("sg5_02", resourceCulture);
            }
        }
        
        public static string sg5_03 {
            get {
                return ResourceManager.GetString("sg5_03", resourceCulture);
            }
        }
        
        public static string sg5_04 {
            get {
                return ResourceManager.GetString("sg5_04", resourceCulture);
            }
        }
        
        public static string sg5_05 {
            get {
                return ResourceManager.GetString("sg5_05", resourceCulture);
            }
        }
        
        public static string sg5_06 {
            get {
                return ResourceManager.GetString("sg5_06", resourceCulture);
            }
        }
        
        public static string sg5_07 {
            get {
                return ResourceManager.GetString("sg5_07", resourceCulture);
            }
        }
        
        public static string sg5_08 {
            get {
                return ResourceManager.GetString("sg5_08", resourceCulture);
            }
        }
        
        public static string sg5_09 {
            get {
                return ResourceManager.GetString("sg5_09", resourceCulture);
            }
        }
        
        public static string sg5_10 {
            get {
                return ResourceManager.GetString("sg5_10", resourceCulture);
            }
        }
        
        public static string sg5_11 {
            get {
                return ResourceManager.GetString("sg5_11", resourceCulture);
            }
        }
        
        public static string sg5_12 {
            get {
                return ResourceManager.GetString("sg5_12", resourceCulture);
            }
        }
        
        public static string sg5_13 {
            get {
                return ResourceManager.GetString("sg5_13", resourceCulture);
            }
        }
        
        public static string DescriptionGroup6 {
            get {
                return ResourceManager.GetString("DescriptionGroup6", resourceCulture);
            }
        }
        
        public static string DescriptionGroup7 {
            get {
                return ResourceManager.GetString("DescriptionGroup7", resourceCulture);
            }
        }
        
        public static string DescriptionGroup8 {
            get {
                return ResourceManager.GetString("DescriptionGroup8", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup6 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup6", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup7 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup7", resourceCulture);
            }
        }
        
        public static string DescriptionTitleGroup8 {
            get {
                return ResourceManager.GetString("DescriptionTitleGroup8", resourceCulture);
            }
        }
        
        public static string sg3 {
            get {
                return ResourceManager.GetString("sg3", resourceCulture);
            }
        }
        
        public static string sg4 {
            get {
                return ResourceManager.GetString("sg4", resourceCulture);
            }
        }
        
        public static string sg6_01 {
            get {
                return ResourceManager.GetString("sg6_01", resourceCulture);
            }
        }
        
        public static string sg6_02 {
            get {
                return ResourceManager.GetString("sg6_02", resourceCulture);
            }
        }
        
        public static string sg6_03 {
            get {
                return ResourceManager.GetString("sg6_03", resourceCulture);
            }
        }
        
        public static string sg6_04 {
            get {
                return ResourceManager.GetString("sg6_04", resourceCulture);
            }
        }
        
        public static string sg6_05 {
            get {
                return ResourceManager.GetString("sg6_05", resourceCulture);
            }
        }
        
        public static string sg6_06 {
            get {
                return ResourceManager.GetString("sg6_06", resourceCulture);
            }
        }
        
        public static string sg6_07 {
            get {
                return ResourceManager.GetString("sg6_07", resourceCulture);
            }
        }
        
        public static string sg6_08 {
            get {
                return ResourceManager.GetString("sg6_08", resourceCulture);
            }
        }
        
        public static string sg6_09 {
            get {
                return ResourceManager.GetString("sg6_09", resourceCulture);
            }
        }
        
        public static string sg6_10 {
            get {
                return ResourceManager.GetString("sg6_10", resourceCulture);
            }
        }
        
        public static string sg6_11 {
            get {
                return ResourceManager.GetString("sg6_11", resourceCulture);
            }
        }
        
        public static string sg6_12 {
            get {
                return ResourceManager.GetString("sg6_12", resourceCulture);
            }
        }
        
        public static string sg7_01 {
            get {
                return ResourceManager.GetString("sg7_01", resourceCulture);
            }
        }
        
        public static string sg7_11 {
            get {
                return ResourceManager.GetString("sg7_11", resourceCulture);
            }
        }
        
        public static string sg8_01 {
            get {
                return ResourceManager.GetString("sg8_01", resourceCulture);
            }
        }
        
        public static string sg8_02 {
            get {
                return ResourceManager.GetString("sg8_02", resourceCulture);
            }
        }
        
        public static string sg8_03 {
            get {
                return ResourceManager.GetString("sg8_03", resourceCulture);
            }
        }
        
        public static string sg8_04 {
            get {
                return ResourceManager.GetString("sg8_04", resourceCulture);
            }
        }
        
        public static string sg8_05 {
            get {
                return ResourceManager.GetString("sg8_05", resourceCulture);
            }
        }
        
        public static string sg8_06 {
            get {
                return ResourceManager.GetString("sg8_06", resourceCulture);
            }
        }
        
        public static string sg8_07 {
            get {
                return ResourceManager.GetString("sg8_07", resourceCulture);
            }
        }
        
        public static string sg8_08 {
            get {
                return ResourceManager.GetString("sg8_08", resourceCulture);
            }
        }
        
        public static string sg8_09 {
            get {
                return ResourceManager.GetString("sg8_09", resourceCulture);
            }
        }
        
        public static string sg8_10 {
            get {
                return ResourceManager.GetString("sg8_10", resourceCulture);
            }
        }
        
        public static string CheckYourself {
            get {
                return ResourceManager.GetString("CheckYourself", resourceCulture);
            }
        }
    }
}
